### ISSUE TITLE
Client connection to sails server

### ISSUE THREAD

**Issue by tremendus** [huafu/ember-data-sails#2]
I'm prototyping with your adapter, thanks for your work on this. 

I'm reaching for some help understanding your setup. 

Setup: 
I have the client served on :4200 (standard ember cli) and the sails serving on :1337 (standard sails config)

Symptom: no model data loads from a model set to use sails adapter via either REST or socket, probably due to a 404 thrown from sails.io.js:2 (the minified socket.io):

```
GET http://0.0.0.0:4200/socket.io/1/?__sails_io_sdk_version=0.10.0&__sails_io_sdk_platform=browser&__sails_io_sdk_language=javascript&t=1422943732164 404 (Not Found)
``` 
I presume this url comes from the sails socket config, where its specified under the 'resource' key '/socket.io'. So why the 404 ... I guess I'm missing something in the configuration?

PS: Output the socket object in sails.io.js:221 shows an object with two events however: socketConnected and onActualSocketConnect. 

So I'm stumped why the 404 and why no data. Any tips would be appreciated.

**Comment by huafu** [comment]
In the adapter(s), you need to setup the host. So in your case I believe the `host` has to be `localhost:1337`. Please reopen this issue if that is not the problem.

**Comment by Kulja** [comment]
I have the same issue but I have `host` set to `localhost:1337`.
Do you have any other ideas?

**Comment by huafu** [comment]
I am actually woking on an update of the adapter to work with sails `0.11`. It'll be also possible to define an other host from the config. So this is an issue now for te socket adapter, but not the rest one. It'll addresses in next verion of this addon, which I believe I'll publish in the incoming days.

**Comment by Kulja** [comment]
Thanks for clearing that up. I'am looking forward to the update.

**Comment by huafu** [comment]
@Kulja I made the changes but I can't find time to fully test it. Can you install the latest version from my repo:
```bash
npm install --save huafu/ember-data-sails#2fa783a4
```
and tell me here if there are any issue. If not I'll publish it.

It is a version working with Sails 0.11 with updated socket and where you can define the host.

**Comment by huafu** [comment]
I forgot to update the README:

For the REST adapter, as the Ember Data one, you specify the host in the `host` property. But for the socket, since it's using my sails socket service, the config needs to be done upward.

So I read a configuration which you can set in `config/environment.js` at `ENV.APP.emberDataSails.socketUrl`. Like this you can configure the host and port there.

**Comment by Kulja** [comment]
I just tried it real quick and can't seem to get it to work.

I set the emberDataSails.socketUrl to sails host and port and the error is gone but now I am getting `Uncaught TypeError: undefined is not a function`.

I am off to bed now, I'll give it a shot tomorrow.

**Comment by huafu** [comment]
can you just send me the trace for it. Because I did test it with basic CRUD and it was actually working. Are you sure you run `ember g ember-data-sails` after installing with npm (I know I forgot to tell you but this command updates the client socket.io that the adapter is using to match the one Sails 0.11 is using)

**Comment by huafu** [comment]
btw, thanks a lot for testing!

**Comment by mickyginger** [comment]
So I've come accross the same problem... Here's the stack

    Uncaught TypeError: undefined is not a function
    __exports__.default.Mixin.create.nextObject
    8.Emitter.emit 												sails.io.js:3
    5.Socket.emit 												sails.io.js:3
    5.Socket.onconnect 											sails.io.js:3
    5.Socket.onpacket 											sails.io.js:3
    7.module.exports 											sails.io.js:3
    8.Emitter.emit 												sails.io.js:3
    3.Manager.ondecoded 										sails.io.js:3
    7.module.exports 											sails.io.js:3
    8.Emitter.emit 												sails.io.js:3
    43.Decoder.add 												sails.io.js:5
    3.Manager.ondata 											sails.io.js:3
    7.module.exports 											sails.io.js:3
    8.Emitter.emit 												sails.io.js:3
    12.Socket.onPacket 											sails.io.js:3
    (anonymous function) 										sails.io.js:3
    8.Emitter.emit 												sails.io.js:3
    13.Transport.onPacket 										sails.io.js:3
    17.Polling.onData.callback 									sails.io.js:4
    (anonymous function) 										sails.io.js:4
    24.exports.decodePayloadAsBinary 							sails.io.js:4
    24.exports.decodePayload 									sails.io.js:4
    17.Polling.onData 											sails.io.js:4
    (anonymous function) 										sails.io.js:4
    8.Emitter.emit 												sails.io.js:3
    16.Request.onData 											sails.io.js:4
    16.Request.onLoad 											sails.io.js:4
    16.Request.create.xhr.onreadystatechange					sails.io.js:4

I've run `ember g ember-data-sails`, and imported the `sails.io.js` in my Brocfile

**Comment by huafu** [comment]
Weird, ok thanks, if I have time today (I am GMT+7, it's 6am here) I'll try to spend some time re-testing by creating an app from scratch.

**Comment by huafu** [comment]
Oh, in which file is this `__exports__.default.Mixin.create.nextObject` happening? you put the files for all other stack items except this one ;-)

**Comment by Kulja** [comment]
Sorry for the delay. I have the exact same output as @mickyginger

**Comment by huafu** [comment]
@Kulja and @mickyginger please provide the line and file where the error i happening (should be the first line ofthe stack in the console)

**Comment by Kulja** [comment]
Although sometime I get this

`Uncaught TypeError: undefined is not a functionember.debug.js:27582 exports.default.mixin.Mixin.create.nextObjectsails.io.js:3 8.Emitter.emitsails.io.js:3 5.Socket.emitsails.io.js:3 5.Socket.onclosesails.io.js:3 7.module.exportssails.io.js:3 8.Emitter.emitsails.io.js:3 3.Manager.onclosesails.io.js:3 7.module.exportssails.io.js:3 8.Emitter.emitsails.io.js:3 12.Socket.onClosesails.io.js:3 12.Socket.onErrorsails.io.js:3 (anonymous function)sails.io.js:3 8.Emitter.emitsails.io.js:3 13.Transport.onErrorsails.io.js:4 (anonymous function)sails.io.js:3 8.Emitter.emitsails.io.js:4 16.Request.onErrorsails.io.js:4 (anonymous function)`

**Comment by mickyginger** [comment]
ember.js:30068

      // overrides Ember.Enumerable version
      nextObject: function(idx) {
        return this.objectAt(idx);
      },

**Comment by huafu** [comment]
Hmmm... very weird, ok I definitely need to debug that myself locally with a fresh project to have the same or almost as you.

**Comment by mickyginger** [comment]
It looks like you are trying to call nextObject on something other than an Ember Enumerable or similar somewhere down the line.

I'm doing this on my route

    model: function() {
        return this.store.find('user');
    }

If I comment that out, the error disappears, so I'm guessing that either I'm using find incorrectly (perhaps I should be using 'on' or 'update' or something), or there's an issue with the adapter's find method

**Comment by huafu** [comment]
Do you guys have disabled extended prototype from Ember? Anyway, hard to test like that. What you have in your route should definitely work. Is that using the socket adapter or the rest adapter? I guess socket of course but just to be sure ;-)

**Comment by Kulja** [comment]
Extended prototype is not disabled and I am using socket adapter of course :)

**Comment by mickyginger** [comment]
Its a brand new Ember app, haven't modified anything apart from adding this add-on.

Yep, using the SocketAdapter, like so:

import DS from 'ember-data';
import SailsSocketAdapter from 'ember-data-sails/adapters/sails-socket';

    export default SailsSocketAdapter.extend({
        useCSRF: true,
        coalesceFindRequests: true
    });

**Comment by Systho** [comment]
I have a very similar problem which I managed to reproduce in my app using a direct load of the page and avoid using multiple transitions to the page. It's very weird but it might help you; I found out that there are way too many callbacks registered for some events.

When I'm using the long path and not have that error, I can type `io.socket._raw._callbacks` and see the few callbacks I'm supposed to view

When I directly load the path and type `io.socket._raw._callbacks` I see more than 80 callbacks registered which looks like all the functions from Ember.Enumerable http://emberjs.com/api/classes/Ember.Enumerable.html

I don't understand how they've managed to land there, though

**Comment by Systho** [comment]
I have continued my investigation and I think the problem comes from this snippet in sails.io.js

```javascript
      // Pass events and a reference to the request queue
      // off to the self._raw for consumption
      for (var evName in self.eventQueue) {
        for (var i in self.eventQueue[evName]) {
          self._raw.on(evName, self.eventQueue[evName][i]);
        }
      }
```

My understanding is that the sails socket can accept to bind event before it even has a socket. In that case it will bind the event on the real socket when it has it. In the meantime those callbacks are stored in the `eventQueue` array.

The problem then is that the eventQueue array is iterated using `for (var i in self.eventQueue[evName])` which brings much more properties than it should because it is not a simple array but an array with Enumerable mixin.

I have thus replaced the snippet by this one

```javascript
// Pass events and a reference to the request queue
      // off to the self._raw for consumption
      for (var evName in self.eventQueue) {
        // for (var i in self.eventQueue[evName]) {
        //   self._raw.on(evName, self.eventQueue[evName][i]);
        // }
        self.eventQueue[evName].forEach(function(callback){
          self._raw.on(evName, callback);
        });
      }
````

which does the job BUT is therefore not compatible anymore with normal arrays.

I'm quite new to Javascript (but I have a strong passive in other languages ) so I'm not sure about the best way to solve this cleanly, but at least you have the explanation and a solution :)

**Comment by huafu** [comment]
thanks @Systho for your investigation. In my previous version, I also had to do a workaround because sails was adding too many listeners on the socket. I thought it had been fixed with this new version, but apparently not. I have a bit of time right now so I am going to work on this. I hope I'll get it working by today, else IDK if I'll be able to work on it again before next week, I am overloaded of work lately...

**Comment by huafu** [comment]
OMG, so the issue here is that if you do not disable Ember prototype extension, it fails for some reason. Disabling Ember prototype extensions makes it works, but might break your application.

I am trying to fix it now, as well as adding many improvements, but it took me a while to figure this out!

**Comment by huafu** [comment]
Voila, fixed with release 0.0.13

**Comment by nrrso** [comment]
I'm prototyping an app and your adapter is a great fit, thanks for the work. However I get an `TypeError: undefined is not a function` from io.sails.**connect** inside of the `_handleSocketReady` method of sails-socket.js (Line 337, Column 36).

```
<exception>: TypeError: undefined is not a function
this: Class
__ember1425904847576: null
__ember_meta__: Object
__nextSuper: undefined
_listeners: Object
_sailsSocket: null
isConnected: false
isInitialized: true
pendingOperationCount: 1
__proto__: Class
waitObject: undefined
```

Previous to the Error, sails logs: 
```
[ed-sails] socket not connected, listening for connect event before giving it
[ed-sails] socket core object ready
[ed-sails] triggering event `didInitialize`
```

Setup: Client's on port 4200 and Server on 1337. SailsRESTAdapter works flawlessly.
Symptom: Can't get socket to connect due to above error.

**Comment by huafu** [comment]
@nrrso can you be sure to use the latest version, and open a new issue if that still does not work with latest version. It should work now, I've tested with both prototype extended and not extended from ember

**Comment by nrrso** [comment]
@huafu yes, i'm using the latest version. After some head scratching i found the reason: it's best to use ember-data-sails with a recent version of sails as for now (tried to replace sails.io.js but this leads to incompatibility issues). 
Was using sails-v0.10.5 with sails.io.js v0.9.16.

Off-Topic: is there a way you accept tips. Your Adapter really helped me save some time.

**Comment by huafu** [comment]
@nrrso oh yeah sorry didn't thought about that. If you want to use a version of sails that is `< 0.11` you have to use the previous version of my adapter: `npm install --save-dev ember-data-sails#0.0.12`, and then run `ember g ember-data-sails`.

For the tips, thanks in advance! If paypal is ok for you, http://huafu.github.io/#/ember (sorry that is all what I have for now).

**Comment by mickyginger** [comment]
Works like a charm. Thanks for all your hard work.

:)
